// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: proto/grps.proto

package grps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// youtuba
type RequestGetData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdUser int32    `protobuf:"varint,1,opt,name=idUser,proto3" json:"idUser,omitempty"`
	Url    []string `protobuf:"bytes,2,rep,name=url,proto3" json:"url,omitempty"`
}

func (x *RequestGetData) Reset() {
	*x = RequestGetData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grps_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetData) ProtoMessage() {}

func (x *RequestGetData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grps_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetData.ProtoReflect.Descriptor instead.
func (*RequestGetData) Descriptor() ([]byte, []int) {
	return file_proto_grps_proto_rawDescGZIP(), []int{0}
}

func (x *RequestGetData) GetIdUser() int32 {
	if x != nil {
		return x.IdUser
	}
	return 0
}

func (x *RequestGetData) GetUrl() []string {
	if x != nil {
		return x.Url
	}
	return nil
}

type ResponseStreamData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdUser   int32    `protobuf:"varint,1,opt,name=idUser,proto3" json:"idUser,omitempty"`
	Urlvideo []string `protobuf:"bytes,2,rep,name=urlvideo,proto3" json:"urlvideo,omitempty"`
}

func (x *ResponseStreamData) Reset() {
	*x = ResponseStreamData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grps_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseStreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStreamData) ProtoMessage() {}

func (x *ResponseStreamData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grps_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStreamData.ProtoReflect.Descriptor instead.
func (*ResponseStreamData) Descriptor() ([]byte, []int) {
	return file_proto_grps_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseStreamData) GetIdUser() int32 {
	if x != nil {
		return x.IdUser
	}
	return 0
}

func (x *ResponseStreamData) GetUrlvideo() []string {
	if x != nil {
		return x.Urlvideo
	}
	return nil
}

// telegram
type IMG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdImg  int32  `protobuf:"varint,1,opt,name=id_img,json=idImg,proto3" json:"id_img,omitempty"`
	UrlImg string `protobuf:"bytes,2,opt,name=url_img,json=urlImg,proto3" json:"url_img,omitempty"`
}

func (x *IMG) Reset() {
	*x = IMG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grps_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMG) ProtoMessage() {}

func (x *IMG) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grps_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMG.ProtoReflect.Descriptor instead.
func (*IMG) Descriptor() ([]byte, []int) {
	return file_proto_grps_proto_rawDescGZIP(), []int{2}
}

func (x *IMG) GetIdImg() int32 {
	if x != nil {
		return x.IdImg
	}
	return 0
}

func (x *IMG) GetUrlImg() string {
	if x != nil {
		return x.UrlImg
	}
	return ""
}

type RequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdUser int32 `protobuf:"varint,1,opt,name=id_user,json=idUser,proto3" json:"id_user,omitempty"`
}

func (x *RequestData) Reset() {
	*x = RequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grps_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestData) ProtoMessage() {}

func (x *RequestData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grps_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestData.ProtoReflect.Descriptor instead.
func (*RequestData) Descriptor() ([]byte, []int) {
	return file_proto_grps_proto_rawDescGZIP(), []int{3}
}

func (x *RequestData) GetIdUser() int32 {
	if x != nil {
		return x.IdUser
	}
	return 0
}

type ResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdData      int32  `protobuf:"varint,1,opt,name=id_data,json=idData,proto3" json:"id_data,omitempty"`
	NameChannel string `protobuf:"bytes,2,opt,name=name_channel,json=nameChannel,proto3" json:"name_channel,omitempty"`
	TextPost    string `protobuf:"bytes,3,opt,name=text_post,json=textPost,proto3" json:"text_post,omitempty"`
	Imgs        []*IMG `protobuf:"bytes,4,rep,name=imgs,proto3" json:"imgs,omitempty"`
}

func (x *ResponseData) Reset() {
	*x = ResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grps_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseData) ProtoMessage() {}

func (x *ResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grps_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseData.ProtoReflect.Descriptor instead.
func (*ResponseData) Descriptor() ([]byte, []int) {
	return file_proto_grps_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseData) GetIdData() int32 {
	if x != nil {
		return x.IdData
	}
	return 0
}

func (x *ResponseData) GetNameChannel() string {
	if x != nil {
		return x.NameChannel
	}
	return ""
}

func (x *ResponseData) GetTextPost() string {
	if x != nil {
		return x.TextPost
	}
	return ""
}

func (x *ResponseData) GetImgs() []*IMG {
	if x != nil {
		return x.Imgs
	}
	return nil
}

var File_proto_grps_proto protoreflect.FileDescriptor

var file_proto_grps_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x4c, 0x69, 0x76, 0x65, 0x56, 0x69, 0x65, 0x77, 0x22, 0x3a, 0x0a, 0x0e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x48, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x75, 0x72, 0x6c, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x22, 0x35, 0x0a, 0x03, 0x49, 0x4d, 0x47, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x64, 0x5f,
	0x69, 0x6d, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x64, 0x49, 0x6d, 0x67,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x72, 0x6c, 0x5f, 0x69, 0x6d, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x72, 0x6c, 0x49, 0x6d, 0x67, 0x22, 0x26, 0x0a, 0x0b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x22, 0x8a, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x6e,
	0x61, 0x6d, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x65, 0x78, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x69,
	0x6d, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4c, 0x69, 0x76, 0x65,
	0x56, 0x69, 0x65, 0x77, 0x2e, 0x49, 0x4d, 0x47, 0x52, 0x04, 0x69, 0x6d, 0x67, 0x73, 0x32, 0x9c,
	0x01, 0x0a, 0x0e, 0x4c, 0x69, 0x76, 0x65, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x12, 0x48, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x59, 0x6f, 0x75, 0x54,
	0x75, 0x62, 0x65, 0x12, 0x18, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x56, 0x69, 0x65, 0x77, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x1c, 0x2e,
	0x4c, 0x69, 0x76, 0x65, 0x56, 0x69, 0x65, 0x77, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x40, 0x0a, 0x0f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x15,
	0x2e, 0x4c, 0x69, 0x76, 0x65, 0x56, 0x69, 0x65, 0x77, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x16, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x56, 0x69, 0x65, 0x77,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42, 0x15, 0x5a,
	0x13, 0x4c, 0x69, 0x76, 0x65, 0x56, 0x69, 0x65, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x72, 0x70, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_grps_proto_rawDescOnce sync.Once
	file_proto_grps_proto_rawDescData = file_proto_grps_proto_rawDesc
)

func file_proto_grps_proto_rawDescGZIP() []byte {
	file_proto_grps_proto_rawDescOnce.Do(func() {
		file_proto_grps_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_grps_proto_rawDescData)
	})
	return file_proto_grps_proto_rawDescData
}

var file_proto_grps_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_grps_proto_goTypes = []interface{}{
	(*RequestGetData)(nil),     // 0: LiveView.RequestGetData
	(*ResponseStreamData)(nil), // 1: LiveView.ResponseStreamData
	(*IMG)(nil),                // 2: LiveView.IMG
	(*RequestData)(nil),        // 3: LiveView.RequestData
	(*ResponseData)(nil),       // 4: LiveView.ResponseData
}
var file_proto_grps_proto_depIdxs = []int32{
	2, // 0: LiveView.ResponseData.imgs:type_name -> LiveView.IMG
	0, // 1: LiveView.LiveViewReturn.ServiceYouTube:input_type -> LiveView.RequestGetData
	3, // 2: LiveView.LiveViewReturn.Servicetelegram:input_type -> LiveView.RequestData
	1, // 3: LiveView.LiveViewReturn.ServiceYouTube:output_type -> LiveView.ResponseStreamData
	4, // 4: LiveView.LiveViewReturn.Servicetelegram:output_type -> LiveView.ResponseData
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_grps_proto_init() }
func file_proto_grps_proto_init() {
	if File_proto_grps_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_grps_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grps_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseStreamData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grps_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grps_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grps_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_grps_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grps_proto_goTypes,
		DependencyIndexes: file_proto_grps_proto_depIdxs,
		MessageInfos:      file_proto_grps_proto_msgTypes,
	}.Build()
	File_proto_grps_proto = out.File
	file_proto_grps_proto_rawDesc = nil
	file_proto_grps_proto_goTypes = nil
	file_proto_grps_proto_depIdxs = nil
}
